services:
  natsbox:
    image: natsio/nats-box
    command: sleep 1d
    environment:
      NATS_URL: nats://ca-montreal-1:4222
      NATS_USER: admin
      NATS_PASSWORD: password
  us-chicago-1:
    command: --config us-chicago-1.json
    volumes:
      - ./conf/us-chicago-1.json:/us-chicago-1.json:ro
      - nats-us-chicago-1:/nats
  us-chicago-2:
    command: --config us-chicago-2.json
    volumes:
      - ./conf/us-chicago-2.json:/us-chicago-2.json:ro
      - nats-us-chicago-2:/nats
  us-chicago-3:
    command: --config us-chicago-3.json
    volumes:
      - ./conf/us-chicago-3.json:/us-chicago-3.json:ro
      - nats-us-chicago-3:/nats
  ca-montreal-1:
    command: --config ca-montreal-1.json
    volumes:
      - ./conf/ca-montreal-1.json:/ca-montreal-1.json:ro
      - nats-ca-montreal-1:/nats
  ca-montreal-2:
    command: --config ca-montreal-2.json
    volumes:
      - ./conf/ca-montreal-2.json:/ca-montreal-2.json:ro
      - nats-ca-montreal-2:/nats
  ca-montreal-3:
    command: --config ca-montreal-3.json
    volumes:
      - ./conf/ca-montreal-3.json:/ca-montreal-3.json:ro
      - nats-ca-montreal-3:/nats
volumes:
  nats-us-chicago-1: {}
  nats-us-chicago-2: {}
  nats-us-chicago-3: {}
  nats-ca-montreal-1: {}
  nats-ca-montreal-2: {}
  nats-ca-montreal-3: {}
